apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferencePolicy
metadata:
  name: missing-ns
spec:
  to:
  - group: ""
    kind: "Service"
  from:
  - group: "gateway.networking.k8s.io"
    kind: "HTTPRoute"
