site_name: Kubernetes Service APIs
repo_url: http://sigs.k8s.io/service-apis
repo_name: GitHub
site_dir: docs
docs_dir: docs-src
theme:
  name: material
plugins:
  - macros:
      include_dir: examples
nav:
  - Introduction: index.md
  - Concepts:
      API concepts: concepts.md
      Security Model: security-model.md
  - Guides:
    - User guide: userguide.md
    - API cookbook: cookbook.md
    - TLS: tls.md
  - References:
    - Releases: releases.md
    - API specification: spec.md
  - Contributing:
    - Developer guide: devguide.md
    - Enhancement requests: enhancement-requests.md
    - Community: community.md
  - FAQ: faq.md
