site_name: Kubernetes Gateway API
repo_url: https://github.com/kubernetes-sigs/gateway-api
repo_name: kubernetes-sigs/gateway-api
site_dir: site
docs_dir: site-src
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/k8s-favicon.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
edit_uri: edit/master/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      include_dir: examples
      j2_line_comment_prefix: "#$"
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
nav:
  - Overview:
    - Introduction: index.md
    - Concepts:
        API overview: concepts/api-overview.md
        Security Model: concepts/security-model.md
        Implementation Guidelines: concepts/guidelines.md
        Versioning: concepts/versioning.md
    - Implementations: implementations.md
    - FAQ: faq.md
  - Guides:
    - Getting started: v1alpha2/guides/getting-started.md
    - Simple Gateway: v1alpha2/guides/simple-gateway.md
    - HTTP routing: v1alpha2/guides/http-routing.md
    - HTTP redirects and rewrites: v1alpha2/guides/http-redirect-rewrite.md
    - HTTP traffic splitting: v1alpha2/guides/traffic-splitting.md
    - Cross-Namespace routing: v1alpha2/guides/multiple-ns.md
    - TLS: v1alpha2/guides/tls.md
    - TCP routing: v1alpha2/guides/tcp.md
  - Reference:
    - API Types:
        GatewayClass: v1alpha2/api-types/gatewayclass.md
        Gateway: v1alpha2/api-types/gateway.md
        HTTPRoute: v1alpha2/api-types/httproute.md
        ReferenceGrant: v1alpha2/api-types/referencegrant.md
    - API specification: v1alpha2/references/spec.md
    - Policy Attachment: v1alpha2/references/policy-attachment.md
    - Enhancement Proposals:
      - Overview: contributing/gep.md
      - ... | geps/gep-*.md
  - Contributing:
    - Developer guide: contributing/devguide.md
    - Enhancement Tracking and Backlog: contributing/enhancement-requests.md
    - Community: contributing/community.md
  - Blog: 
    - Index: blog/index.md
    - 2021:
      - blog/2021/introducing-v1alpha2.md
