site_name: Kubernetes Gateway API
repo_url: https://github.com/kubernetes-sigs/gateway-api
repo_name: kubernetes-sigs/gateway-api
site_dir: site
docs_dir: site-src
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.highlight
edit_uri: edit/master/site-src/
extra_css:
  - css/extra.css
plugins:
  - search
  - awesome-pages
  - macros:
      include_dir: examples
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Concepts:
      API overview: concepts/api-overview.md
      Security Model: concepts/security-model.md
      Implementation Guidelines: concepts/guidelines.md
  - API Types:
      GatewayClass: api-types/gatewayclass.md
      Gateway: api-types/gateway.md
      HTTPRoute: api-types/httproute.md
  - Guides:
    - Getting started: guides/getting-started.md
    - Simple Gateway: guides/simple-gateway.md
    - HTTP routing: guides/http-routing.md
    - HTTP traffic splitting: guides/traffic-splitting.md
    - Multiple namespaces and routes: guides/multiple-ns.md
    - TLS: guides/tls.md
    - TCP routing: guides/tcp.md
  - References:
    - API specification: references/spec.md
    - Releases: references/releases.md
    - Implementations: references/implementations.md
  - ... | geps/gep-*.md
  - Contributing:
    - Developer guide: contributing/devguide.md
    - Gateway Enhancement Proposal: contributing/gep.md
    - Enhancement requests: contributing/enhancement-requests.md
    - Community: contributing/community.md
  - FAQ: faq.md

