site_name: Kubernetes Gateway API
repo_url: http://sigs.k8s.io/gateway-api
repo_name: GitHub
site_dir: site
docs_dir: site-src
theme:
  name: material
plugins:
  - search
  - macros:
      include_dir: examples
nav:
  - Introduction: index.md
  - Concepts:
      API overview: api-overview.md
      Security Model: security-model.md
      Implementation Guidelines: guidelines.md
  - API Types:
      GatewayClass: gatewayclass.md
      Gateway: gateway.md
      HTTPRoute: httproute.md
  - Guides:
      - Introduction: guides.md
      - Getting started: getting-started.md
      - Simple Gateway: simple-gateway.md
      - HTTP routing: http-routing.md
      - HTTP traffic splitting: traffic-splitting.md
      - Multiple namespaces and routes: multiple-ns.md
      - TLS: tls.md
      - TCP routing: tcp.md
  - References:
      - API specification: spec.md
      - Releases: releases.md
  - Contributing:
      - Developer guide: devguide.md
      - Enhancement requests: enhancement-requests.md
      - Community: community.md
  - FAQ: faq.md

