# Netlify build instructions
[build]
    command = "make docs"
    publish = "docs"
    environment = { PYTHON_VERSION = "3.7" }

# Standard Netlify redirects
[[redirects]]
    from = "https://master--kubernetes-sigs-gateway-api.netlify.com/*"
    to = "https://master.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://master.gateway-api.sigs.k8s.io/*"
    to = "https://master.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://master--kubernetes-sigs-gateway-api.netlify.com/*"
    to = "http://master.gateway-api.sigs.k8s.io/:splat"
    status = 301
    force = true
