apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway-sample
spec:
  class: gatewayclass-sample
  addresses:
  - type: IPAddress
    value: 1.2.3.4
  listeners:
  - port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: v1
        resource: secrets
        name: gateway-sample
      minimumVersion: TLS_1_0
      options:
        gateway-controller.vendor.x-k8s.io/tls-option-1: value1
        gateway-controller.vendor.x-k8s.io/tls-option-2: value2
    routes:
      routeNamespaces:
        namespaceSelector:
          matchLabels:
            env: prod
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: web
