kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: acme-lb
spec:
  controller: acme.io/gateway-controller
  parametersRef:
    name: acme-lb
    group: acme.io
    kind: Parameters
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClassName: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: TCP
    port: 8080
    routes:
      kind: TCPRoute
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          "app": "foo"
---
kind: TCPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: tcp-app-1
  namespace: default
  labels:
    app: foo
spec:
  rules:
  - forwardTo:
    - serviceName: my-service
