kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: acme-lb
spec:
  controller: acme.io/gateway-controller
  parametersRef:
    name: acme-lb
    group: acme.io
    resource: parameters
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClassName: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: HTTP
    routes:
      resource: httproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: foo
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-app-1
  namespace: default
  labels:
    app: foo
spec:
  hosts:
  - hostnames:
    - "foo.com"
    rules:
    - match:
        path:
          type: Prefix
          value: /bar
      action:
        forwardTo:
          - targetRef:
              name: my-service
              group: core
              resource: services
    - match:
        headers:
          type: Exact
          values:
            x-forwarded-proto: https
            magic: foo
        path:
          type: Prefix
          value: /some/thing
      action:
        forwardTo:
          - targetRef:
              name: my-service
              group: core
              resource: services
