kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: default-match-example
spec:
  controller: acme.io/gateway-controller

---

kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: default-match-gw
  namespace: default
spec:
  class: default-match-example
  listeners:
  - protocol: HTTP
    routes:
      resource: httproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: default-match

---

# This HTTPRoute demonstrates patch match defaulting. If no path match is
# specified, CRD defaults adds a default prefix match on the path "/". This
# matches every HTTP request and ensures that route rules always have at
# least one valid match.
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: default-match-route
  namespace: default
  labels:
    app: default-match
spec:
  hosts:
  - hostnames:
    - default-match.com
    rules:
    - matches:
      - headers:
          type: Exact
          values:
            magic: default-match
      action:
        forwardTo:
          - targetRef:
              name: my-service
              group: core
              resource: services
    - matches:
      - path:
          type: Exact
          value: /example/exact
      action:
        forwardTo:
          - targetRef:
              name: my-service
              group: core
              resource: services
    - action:
        forwardTo:
          - targetRef:
              name: my-service
              group: core
              resource: services

