kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: default-class
  addresses:
  - type: NamedAddress
    value: auto-assign
  listeners:
  # Forward port 22 to a SSH honeypot app.
  - port: 22
    protocol: TCP
    routes:
      resource: tcproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: sshd-honeypot
  # Forward port 2222 to a real SSH server.
  - port: 2222
    protocol: TCP
    routes:
      resource: tcproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: sshd-legitimate
  # Forward the SNI named service to the real SSH server ever TLS, assuming
  # that there is an actual client for such a beast.
  - hostname:
      match: Exact
      name: ssh.example.com
    port: 443
    protocol: TLS
    tls:
      options: {}
      certificateRef:
        name: ssh-server
        resource: secrets
        group: core
    routes:
      resource: tcproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: sshd-legitimate
