kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: default-class
  addresses:
  - type: NamedAddress
    value: auto-assign
  listeners:
  - hostname:
      name: httpbin.example.com
    port: 80
    protocol: HTTP
    routes:
      kind: HTTPRoute
      routeNamespaces:
        from: "All"
      routeSelector:
        matchLabels:
          app: httpbin
