kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: gateway
  namespace: default
spec:
  class: default-class
  addresses:
  - type: NamedAddress
    value: auto-assign
  listeners:
  - hostname:
      match: Domain
      name: example.com
    port: 443
    protocol: HTTPS
    tls:
      options: {}
      certificateRefs:
      - name: example-wildcard
        resource: secrets
        group: core
    routes:
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          # This label selects httpbin.example.com and
          # conformance.example.com routes.
          app: httpbin-or-conformance
