resources:
- standard/gateway.networking.k8s.io_gatewayclasses.yaml
- standard/gateway.networking.k8s.io_gateways.yaml
- standard/gateway.networking.k8s.io_httproutes.yaml
- gateway.networking.k8s.io_referencegrants.yaml
